version: '3.7'

services:
  app:
    build: .
    image: az204sandbox
    environment:
      AzureWebJobsScriptRoot: /home/site/wwwroot
      AzureFunctionsJobHost__Logging__Console__IsEnabled: true
    ports:
      - 80:80
